# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c2cbce069057f24c91c8cfb020ac953968109bc774e4fe69471e59753bb6f916968c56de53cf329d83fcb76e4509ae17fe0155029030fa8be0db637f880e275b

test:
  secret_key_base: 16f36287137590ab089f41e7e873a1aa48d8d79a2f891d446b075f5d2fd749c309458bae88c5b6a981f93d9186fc46cc7fc71748904cdbb244135d550a839632

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
